---
packit_instances: ["prod", "stg"]

upstream_project_url: https://github.com/packit/specfile
issue_repository: https://github.com/packit/specfile

# PEP440
prerelease_suffix_pattern: "([.\\-_]?)(a(lpha)?|b(eta)?|r?c|pre(view)?)([.\\-_]?\\d+)?"
prerelease_suffix_macro: prerelease

copy_upstream_release_description: true

packages:
  specfile:
    upstream_package_name: specfile
    downstream_package_name: python-specfile
    specfile_path: &specfile_path fedora/python-specfile.spec
    files_to_sync:
      - *specfile_path
      - .packit.yaml
      - src: plans/
        dest: plans/
      - src: .fmf/
        dest: .fmf/
    srpm_build_deps:
      - python3-build
      - python3-setuptools_scm
    actions:
      pre-sync:
        - python3 plans/git_reference.py
      create-archive:
        - python3 -m build --sdist --outdir ./fedora/
        - bash -c "ls -1t ./fedora/*.tar.gz | head -n 1"
      get-current-version: python3 -m setuptools_scm

  # docs: https://gitlab.com/CentOS/Integration/packit-cbs/docs
  specfile-centos-integration-sig:
    upstream_package_name: specfile
    downstream_package_name: python-specfile
    specfile_path: &specfile_path_centos centos-integration-sig/python-specfile.spec
    files_to_sync:
      - *specfile_path_centos
      - .packit.yaml
      - src: plans/
        dest: plans/
      - src: .fmf/
        dest: .fmf/
    srpm_build_deps:
      - python3-build
      - python3-setuptools_scm
    actions:
      pre-sync:
        - python3 plans/git_reference.py
      create-archive:
        - python3 -m build --sdist --outdir ./fedora/
        - bash -c "ls -1t ./centos-integration-sig/*.tar.gz | head -n 1"
      get-current-version: python3 -m setuptools_scm
    dist_git_base_url: https://gitlab.com # this is not taken into account by centpkg-sig yet!
    dist_git_namespace: CentOS/Integration/packit-cbs/rpms # this is not taken into account by centpkg-sig yet!
    #sig: Integration/packit-cbs # this is not taken into account by centpkg-sig yet!
    pkg_tool: centpkg-sig

  specfile-epel8:
    upstream_package_name: specfile
    downstream_package_name: python-specfile
    specfile_path: &specfile_path_epel8 epel8/python-specfile.spec
    files_to_sync:
      - *specfile_path_epel8
      - .packit.yaml
      - src: plans/
        dest: plans/
      - src: .fmf/
        dest: .fmf/
    srpm_build_deps:
      - python3-setuptools_scm
    actions:
      pre-sync:
        - python3 plans/git_reference.py
      create-archive:
        - python3 setup.py sdist --dist-dir ./epel8/
        - bash -c "ls -1t ./epel8/*.tar.gz | head -n 1"
      get-current-version: python3 setup.py --version

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [specfile]
    preserve_project: true
    targets:
      - fedora-all
      - epel-9
  - job: copr_build
    trigger: pull_request
    packages: [specfile-epel8]
    targets:
      - epel-8

  - job: copr_build
    trigger: commit
    branch: main
    packages: [specfile]
    targets:
      - fedora-all
      - epel-9
    project: packit-dev
    list_on_homepage: True
    preserve_project: True
  - job: copr_build
    trigger: commit
    branch: main
    packages: [specfile-epel8]
    targets:
      - epel-8
    project: packit-dev
    list_on_homepage: True
    preserve_project: True

  - job: copr_build
    trigger: commit
    branch: stable
    packages: [specfile]
    targets:
      - fedora-stable
      - epel-9
    project: packit-stable
    list_on_homepage: True
    preserve_project: True
  - job: copr_build
    trigger: commit
    branch: stable
    packages: [specfile-epel8]
    targets:
      - epel-8
    project: packit-stable
    list_on_homepage: True
    preserve_project: True

  - job: copr_build
    trigger: release
    packages: [specfile]
    targets:
      - fedora-all
      - epel-9
    project: packit-releases
    list_on_homepage: True
    preserve_project: True
  - job: copr_build
    trigger: release
    packages: [specfile-epel8]
    targets:
      - epel-8
    project: packit-releases
    list_on_homepage: True
    preserve_project: True

  - job: tests
    trigger: pull_request
    packages: [specfile]
    tmt_plan: "smoke|full|packit-integration"
    targets:
      - fedora-all
      - epel-9
  - job: tests
    trigger: pull_request
    packages: [specfile-epel8]
    tmt_plan: "smoke|full"
    use_internal_tf: true
    targets:
      epel-8:
        distros: [RHEL-8]
    # enable EPEL
    tf_extra_params:
      environments:
        - kickstart:
            post-install: |
              %post --log=/dev/console
              set -x
              dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
              %end

  - job: tests
    trigger: pull_request
    packages: [specfile]
    identifier: performance
    tmt_plan: performance
    targets:
      - fedora-rawhide

  - job: propose_downstream
    trigger: release
    packages: [specfile]
    dist_git_branches:
      rawhide:
        fast_forward_merge_into:
          - fedora-branched
      epel-9: {}
  - job: propose_downstream
    trigger: release
    packages: [specfile-epel8]
    dist_git_branches:
      - epel-8
  - job: propose_downstream
    trigger: release
    packages: [specfile-centos-integration-sig]
    dist_git_branches:
      - c9-sig-integration

  - job: pull_from_upstream
    trigger: release
    packages: [specfile]
    dist_git_branches:
      rawhide:
        fast_forward_merge_into:
          - fedora-branched
      epel-9: {}
  - job: pull_from_upstream
    trigger: release
    packages: [specfile-epel8]
    dist_git_branches:
      - epel-8
  - job: pull_from_upstream
    trigger: release
    packages: [specfile-centos-integration-sig]
    dist_git_branches:
      - c9-sig-integration

  - job: koji_build
    trigger: commit
    packages: [specfile]
    packit_instances: ["stg"]
    allowed_pr_authors: ["packit-stg", "packit"]
    sidetag_group: packit-specfile-ogr-releases
    dependents:
      - packit
    dist_git_branches:
      - fedora-all
      - epel-9
  - job: koji_build
    trigger: commit
    packages: [specfile-epel8]
    packit_instances: ["stg"]
    allowed_pr_authors: ["packit-stg", "packit"]
    dist_git_branches:
      - epel-8
  - job: koji_build
    trigger: commit
    packages: [specfile-centos-integration-sig]
    packit_instances: ["stg"]
    allowed_pr_authors: ["packit-stg", "packit"]
    dist_git_branches:
      - c9-sig-integration

  - job: bodhi_update
    trigger: commit
    packages: [specfile-epel8]
    packit_instances: ["stg"]
    allowed_builders: ["packit-stg", "packit"]
    dist_git_branches:
      - epel-8
