---
packit_instances: ["prod", "stg"]

upstream_project_url: https://github.com/packit/specfile
issue_repository: https://github.com/packit/specfile

# PEP440
prerelease_suffix_pattern: "([.\\-_]?)(a(lpha)?|b(eta)?|r?c|pre(view)?)([.\\-_]?\\d+)?"
prerelease_suffix_macro: prerelease

copy_upstream_release_description: true

packages:
  specfile:
    upstream_package_name: specfile
    downstream_package_name: python-specfile
    specfile_path: &specfile_path fedora/python-specfile.spec
    files_to_sync:
      - *specfile_path
      - .packit.yaml
      - src: plans/
        dest: plans/
      - src: .fmf/
        dest: .fmf/
    srpm_build_deps:
      - python3-build
      - python3-setuptools_scm
    actions:
      pre-sync:
        - python3 plans/git_reference.py
      create-archive:
        - python3 -m build --sdist --outdir ./fedora/
        - bash -c "ls -1t ./fedora/*.tar.gz | head -n 1"
      get-current-version: python3 -m setuptools_scm

  specfile-epel8:
    upstream_package_name: specfile
    downstream_package_name: python-specfile
    specfile_path: &specfile_path_epel8 epel8/python-specfile.spec
    files_to_sync:
      - *specfile_path_epel8
      - .packit.yaml
      - src: plans/
        dest: plans/
      - src: .fmf/
        dest: .fmf/
    srpm_build_deps:
      - python3-setuptools_scm
    actions:
      pre-sync:
        - python3 plans/git_reference.py
      create-archive:
        - python3 setup.py sdist --dist-dir ./epel8/
        - bash -c "ls -1t ./epel8/*.tar.gz | head -n 1"
      get-current-version: python3 setup.py --version

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [specfile]
    owner: nforro
    targets:
      - fedora-all
      - epel-9
  - job: copr_build
    trigger: pull_request
    packages: [specfile-epel8]
    owner: nforro
    project: debug
    targets:
      - epel-8
